/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleaseRouteImport } from './routes/release'
import { Route as EpisodesSarahRouteImport } from './routes/episodes.sarah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseRoute = ReleaseRouteImport.update({
  id: '/release',
  path: '/release',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesSarahRoute = EpisodesSarahRouteImport.update({
  id: '/episodes/sarah',
  path: '/episodes/sarah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/release': typeof ReleaseRoute
  '/episodes/sarah': typeof EpisodesSarahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/release': typeof ReleaseRoute
  '/episodes/sarah': typeof EpisodesSarahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/release': typeof ReleaseRoute
  '/episodes/sarah': typeof EpisodesSarahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/release' | '/episodes/sarah'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/release' | '/episodes/sarah'
  id: '__root__' | '/' | '/release' | '/episodes/sarah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReleaseRoute: typeof ReleaseRoute
  EpisodesSarahRoute: typeof EpisodesSarahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release': {
      id: '/release'
      path: '/release'
      fullPath: '/release'
      preLoaderRoute: typeof ReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes/sarah': {
      id: '/episodes/sarah'
      path: '/episodes/sarah'
      fullPath: '/episodes/sarah'
      preLoaderRoute: typeof EpisodesSarahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReleaseRoute: ReleaseRoute,
  EpisodesSarahRoute: EpisodesSarahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
